spring.application.name=BloomCart
spring.datasource.url=jdbc:postgresql://localhost:5432/BloomCartDB
spring.datasource.username=postgres
spring.datasource.password=Chandanpreet@2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

